openapi: "3.0.0"
info:
  description: Employer administration back-end
  version: "1.0.0"
  title: Swaggable Example
  contact:
    name: Morten Hekkvang
    email: morten.hekkvang@gmail.com
  license:
    name: The Unlicense
    url: http://unlicense.org/
servers:
  - url: http://swaggable.artheus.se/api
